### ISSUE TITLE
ACPI error with _LID function

### ISSUE THREAD

**Issue by brs17** [system76/ec#10]
On the galp4 and darp6 running this EC, after logging in, after 30 seconds or so, the scaling on the display goes from 100% to 200%. This does not happen if the HiDPI daemon is off, or on a darp6 without the open EC. 

The error returned via dmesg:

```ACPI Error: Aborting method \_SB.LID0._LID due to previous error (AE_TIME) (20190703/psparse-531)```

**Comment by jackpot51** [comment]
Merged with #12

**Comment by jackpot51** [comment]
I haven't seen this in a while, has anyone else? @brs17 @crawfxrd  @leviport @WatchMkr

**Comment by crawfxrd** [comment]
I still see this on the galp3-c.

**Comment by jackpot51** [comment]
Does it happen without parallel debug?

**Comment by crawfxrd** [comment]
Yes. On d96147688d6e7 with all debugging disabled I still get these messages.

**Comment by jackpot51** [comment]
Interesting

**Comment by brs17** [comment]
I don't think I had seen this either recently on a galp4.

**Comment by jackpot51** [comment]
Will close until it comes back.
