### ISSUE TITLE
Implement max fan keypress

### ISSUE THREAD

**Issue by jackpot51** [system76/ec#103]
This used to be fn+1. It could be the start of a manual fan control framework

**Comment by WatchMkr** [comment]
I recall regular support request from customers accidentally hitting the FN+1 combination.

Understanding how it might be used would help decide the best way to provide a max-fan feature (if at all).

**Comment by jackpot51** [comment]
Support has stated that they prefer the small number of complaints about accidentally hitting it to being unable to test fans easily. It is also possible that having support for writing fan duty cycle from the OS would solve this problem, but is harder to implement

**Comment by WatchMkr** [comment]
Got it. Let's use a three-key combo to allow testing and avoid accidentally turning on the fans to max. FN+Shift+1?

**Comment by jackpot51** [comment]
I like two handed keypresses to avoid issues. Any thoughts on a right handed key that could be used?

**Comment by WatchMkr** [comment]
Either side could be used with Shift in the combo. Keeping FN and 1 is good so that if it's not one (old stuff) add Shift (new stuff).

**Comment by curiousercreative** [comment]
Was this issue resolved?

**Comment by jackpot51** [comment]
Yes, it was resolved. Fn-1 triggers maximum fan speed
