### ISSUE TITLE
Invalid battery stats

### ISSUE THREAD

**Issue by shalzz** [system76/ec#11]
With the current vendor EC more than often after resuming from a suspend the battery level stats are wildly off the actual value. See:
![Screenshot from 2019-12-28 11-19-15](https://user-images.githubusercontent.com/3907269/71539613-ccf07300-2964-11ea-865a-6fec412eaa15.png)

After suspending with battery charge percentage around 90% and resuming after a few hours (5-6 Hrs) the OS sees the battery percentage at around 5-1%. Plugging in and out the ac adapter a couple of times resets the battery stats to it's actual value. (You can see this happening at the 2m mark, where the battery level goes from 5% to 10% then 87% within a few seconds).

I have seen this happen intermittently for the past year. I hope this issue can be fixed in the OSS version?

Machine info:
dmidecode: https://paste.rs/osx

Let me know if you need any more info.

**Comment by jackpot51** [comment]
I have not seen this issue with the open source firmware
