### ISSUE TITLE
lemp9 SCI keys don't work after suspend

### ISSUE THREAD

**Issue by davidlattimore** [system76/ec#132]
I just discovered the custom keyboard layout instructions. Thanks, they're awesome!

After flashing and subsequently suspending, I found that the brightness keys weren't working. The airplane safe and suspend keys weren't working either. It looks like these are the keys referred to as SCI keys in keymap.h.

I tried reverting to the default keyboard layout and the same thing happened - after reboot, the SCI keys worked, but then after suspend, they didn't.

I tracked this down to 00043ebfaffb9c9673b73a050040b85bcf2286d3. I'm now running at head, with that commit reverted and everything seems to be working well.

I'm running a Lemur Pro with Pop OS 20.10.

**Comment by jackpot51** [comment]
If you update the ec you also need to update coreboot. It has an ACPI change that is required for that commit to work
