### ISSUE TITLE
galp5: fans remain at 100% during suspend

### ISSUE THREAD

**Issue by leviport** [system76/ec#170]
If I set the fans at 100% with the Fn + 1 hotkey and suspend the machine, it will suspend, but the fans stay spinning at 100% while it sleeps. I can also turn them on and off with the machine suspended without it waking up. I think the hotkey should probably be ignored while suspended, and the fans should probably turn off when entering suspend.

**Comment by jackpot51** [comment]
Does this affect other models?

**Comment by leviport** [comment]
Oryp7 doesn't do it. The machine wakes up when I hit Fn, so I can't turn them on while it's asleep. They also turn off when entering suspend, although resuming briefly makes them spin up fast for half a second before returning to the default mode. 

If it's related to SI0x, I'm betting darp7 and lemp10 would do the same thing.

**Comment by jackpot51** [comment]
I think it is related to S0ix. Does the power LED pulse as though it is suspended while this is happening?

**Comment by leviport** [comment]
Yes, though I see the sequence reset when I hit the hotkey.

**Comment by jacobgkau** [comment]
> If it's related to SI0x, I'm betting darp7 and lemp10 would do the same thing.

Just to confirm, I can recreate this on darp7 and lemp10.
