### ISSUE TITLE
Problem with build instructions

### ISSUE THREAD

**Issue by davidskeck** [system76/ec#191]
Hello,

I am having an issue with the build instructions in [`keyboard-layout-customization`](https://github.com/system76/ec/blob/master/doc/keyboard-layout-customization.md).

I have followed the instructions as best as I know how, but I have a few issues.

I have a `config.mk` file in the `ec/` directory, and I am calling `make`.

Here's the result of calling `make`:
![image](https://user-images.githubusercontent.com/1740630/117583798-ccc2c480-b0ce-11eb-8a80-038fabb3d90b.png)

But, this version does not match my currently installed version:
![image](https://user-images.githubusercontent.com/1740630/117583808-db10e080-b0ce-11eb-94e8-3f7321470bd8.png)

Even though I am on the right commit from `firmware-open`:

![image](https://user-images.githubusercontent.com/1740630/117583838-127f8d00-b0cf-11eb-8c6d-c6626a25d6a3.png)

It does match the commit in `ec`:
![image](https://user-images.githubusercontent.com/1740630/117583999-fa5c3d80-b0cf-11eb-965d-065bbe3adcd6.png)

Is this the correct way to build, even though the version info seems to mismatch?

Thank you!

**Comment by davidskeck** [comment]
I just tried flashing the result of the make instruction and my new keymap worked. I'm guessing the version number doesn't have to match the report from the System Firmware tool. The firmware version reported by that tool also hasn't changed. I'll leave this open in case anyone wants to verify that the mismatched versions are OK. So far I don't have any issues.

**Comment by crawfxrd** [comment]
Yes. firmware-manager reports the system firmware version. This is the information reported in the DMI table, which you can see with `sudo dmidecode -t bios`.

The EC version, specifically, can be determined with
```
./scripts/ectool.sh info
```

- If building/flashing EC firmware from firmware-open, the version of the EC firmware is [set to match the version of the system firmware](https://github.com/system76/firmware-open/blob/0905c82add536432a7a621992881dadc65e14177/scripts/build.sh#L99)
- If building/flashing the EC firmware from this repo, then it will have a different version than the system firmware

**Comment by davidskeck** [comment]
Thank you, @crawfxrd. That clears this up for me!
