### ISSUE TITLE
Pause/Break not implemented, through printed on the keys for several models

### ISSUE THREAD

**Issue by ids1024** [system76/ec#197]
This appears on the "PgUp" and "PgDn" keys at the top right of several models with numpads.

Apparently "Break" on a PC is really `Ctrl + Pause`. Usually it is not a separate key. I haven't tested with proprietary firmware, but I would guess `fn + PgUp` sends `Pause`, and `fn + PgDn` sends `Ctrl` and `Pause`.

Not sure what behavior we really want, and these keys aren't very important, but probably `Pause` should at least be an option in the Configurator.

**Comment by MilesBHuff** [comment]
Can confirm:  I discovered this around the same time you did when I was writing [the Arch Wiki article for the Oryx Pro series](https://wiki.archlinux.org/title/System76_Oryx_Pro#Function_keys).
![image](https://user-images.githubusercontent.com/6566982/169742415-d6cb8ac9-b46c-44ab-a129-ed92ca4036b0.png)
At present, the Fn key seems to fall through on the Pause/Break keys, and we get PgUp or PgDn instead.
