### ISSUE TITLE
galp4 removing a USB device from the left port initiates shutdown dialog

### ISSUE THREAD

**Issue by WatchMkr** [system76/ec#2]

**Comment by jackpot51** [comment]
Does this still happen?

**Comment by leviport** [comment]
Can you check the bottom panel screws on the bottom of the machine? If the one nearest to the power button is loose or missing, the movement of the motherboard and the case can push the power button. Open EC's lessening of the power button debounce may exacerbate the issue though.

**Comment by WatchMkr** [comment]
This isn't happening on my galp4 any longer.
