### ISSUE TITLE
How to define keycode for "scroll lock"?

### ISSUE THREAD

**Issue by larsblumberg** [system76/ec#223]
I use the `Scroll Lock` key as the "compose key" to type "special characters" on Pop_OS! (configurable via _Settings > Keyboard > Type Special Characters_).

The firmware currently doesn't define key codes for the scroll lock key as documented here:

https://github.com/system76/ec/blob/c7fafe01038d3adbc9893cd5ed2214f5424563bb/src/common/include/common/keymap.h#L170

I'd like to map the `Fn + Print Screen` key to `Scroll Lock`.

Is there a chance to find and define the corresponding key codes myself or is there more engineering effort involved than just defining the codes?

**Comment by crawfxrd** [comment]
Scroll lock can now be defined with `K_SCROLL_LOCK` in the keymap.

**Comment by larsblumberg** [comment]
Thanks a ton @crawfxrd!

**Comment by larsblumberg** [comment]
@crawfxrd Just wanted to confirm that I can type special characters now (such as German umlauts) using the Scroll Lock key on my lemp10. Thanks again for your changes once more.
