### ISSUE TITLE
darp6: System fails second suspend

### ISSUE THREAD

**Issue by crawfxrd** [system76/ec#23]
Version: [2020-02-18_f7453df](https://github.com/system76/ec/commit/f7453df)
Target: `system76/darp5`

**Steps to reproduce**:
- Press `Fn`+`F12` to sleep
- Power Power button to wake
- Press `Fn`+`F12` to sleep

**Expected behavior**:
- screen turns off
- power button turns off
- power status LED blinks green
- system can be resumed by pressing power button

**Actual behavior**:
- screen turns off
- power button is _on_
- power status LED is _solid_ green
- system cannot be resumed

**Comment by brs17** [comment]
Did you find you needed to be unplugged from AC power to replicate this?

**Comment by brs17** [comment]
This issue was also replicated on the galp4 and darp6.

**Comment by crawfxrd** [comment]
No, I'm AC power.

`ecflash/ec.py` is also failing to read the EC version on the darp6.

**Comment by jackpot51** [comment]
You guys have open and proprietary EC mixed up. @brs17 saw this behaviour on proprietary EC. @crawfxrd saw this behaviour on open EC. The ec.py script is not adapted for the open EC yet.

**Comment by jackpot51** [comment]
This could point to it being a coreboot issue

**Comment by crawfxrd** [comment]
Closing in favor of #31
