### ISSUE TITLE
darp7: suspend when docked spins fans indefinitelly and consumes lots of energy

### ISSUE THREAD

**Issue by pspacek** [system76/ec#238]
Versions affected: 2021-04-07_236914e and also 2021-07-20_93c2809

Docking station in use: i-tec [C31DUALDPDOCKPD](https://i-tec.pro/en/produkt/c31dualdpdockpd-2/) (USB-C, Thunderbolt-3 docking station)

Expected behavior:
Laptop suspends, is silent, and does not consume much power.

Reproducer variant A:
1. Connect laptop to dock
2. Suspending laptop via `systemctl suspend`

What happens A:
- Keyboard backlight switches off
- Power LED stays on (does not start blinking as it normally does in suspend)
- In a second or two fans start spinning and keep spinning indefinitely
- Power consumption stays around ~ 5 W (i.e. significantly more than suspended state without dock, because my power meter shows 0 W for suspend without laptop - possibly an inaccuracy on power meter side)

Reproducer variant B:
1. Suspending laptop via `systemctl suspend` while not connected to anything
2. Connect laptop to dock
3. Observe
4. Disconnect laptop from dock

What happens B:
- Keyboard backlight switches off
- Power LED starts blinking as it should
- /now connect dock at this point/
- Power LED turns on (= stops blinking) but keyboard backlight stays off
- In a second or two fans start spinning and keep spinning indefinitely
- Power consumption jumps up to around ~ 5 W
- /now disconnect dock again while the system is still suspended/
- Fans stop
- Power LED starts blinking again
- Power consumption goes back to near 0 levels

Additional observations:
- fans spin down right after wake up
- dock works after wake up

Variables which do not make a difference:
- power adapter not/connected to the laptop
- power delivery from docking station not/available (the docker can either do PD or draw power from laptop)
- docking station powered on/off (button on the dock)
- any peripherals connected do docking station (happens even with all ports unplugged and dock switched off)
- PopOS airplane mode on/off
- keyboard backlight state on/off

I would be happy to supply additional information if you instruct me how to gather them.

**Comment by crawfxrd** [comment]
This is being tracked at system76/firmware-open#199.
