### ISSUE TITLE
The oryp6 power lamp is not on

### ISSUE THREAD

**Issue by FTKyaoyuan** [system76/ec#251]
We flashed the bios and ec of oryp6, but the power indicator did not light up when we started. We compared the pin function of gpio.c and our circuit diagram to be exactly the same, and we could not confirm the problem.

**Comment by jacobgkau** [comment]
What's the System76 serial number of your machine? If you prefer not to provide it publicly, you are also welcome to open a [support ticket](https://support.system76.com/) instead if the power LED isn't working. Does it work if you revert back to the stable firmware?

**Comment by jackpot51** [comment]
@FTKyaoyuan if you do not have a genuine System76 product, you should not create issues claiming there are problems with our firmware.
