### ISSUE TITLE
ectool forces static hidraw for hidapi crate

### ISSUE THREAD

**Issue by Conan-Kudo** [system76/ec#257]
While [reviewing this package for inclusion in Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2022178), I noticed that it forces the `linux-static-hidraw` feature instead of the `linux-shared-hidraw` feature from the `hidapi` crate. In Fedora, we'd prefer that C libraries be dynamically linked for these kinds of things.

Please consider switching the requested feature of the `hidapi` crate to `linux-shared-hidraw`.

**Comment by jackpot51** [comment]
@ids1024 was there a reason we used the `linux-static-hidraw` feature?

**Comment by jackpot51** [comment]
https://github.com/system76/ec/commit/f4458aebcafefb3a9aea8bd18d6ede29cb192a04 was when this was added

**Comment by ids1024** [comment]
I commented on https://github.com/pop-os/keyboard-configurator/issues/107 earlier.

The `hidapi` crate uses `linux-static-libusb` by default, so when I switched to the hidraw backend I left it with static linking. But dynamic linking should be fine.

**Comment by jackpot51** [comment]
Released as system76_ectool version 0.3.7
