### ISSUE TITLE
mega2560.MD still up to date?

### ISSUE THREAD

**Issue by trevor87** [system76/ec#278]
Hi!

I have a question regarding the information on https://github.com/system76/ec/blob/master/doc/mega2560.md

It states that the 0.5mm pitch connector is only used for the lemp9. Is that correct? Or should it not also name the lemp10?

**Comment by crawfxrd** [comment]
Yes, that could just say `lemp`. It has the same design, using a 0.5mm pitch FPC cable.

**Comment by crawfxrd** [comment]
Wording changed in 60dfb62f90e0.
