### ISSUE TITLE
lemp9: Right click on touchpad

### ISSUE THREAD

**Issue by brs17** [system76/ec#28]
With the strong majority of my experience coming from laptops with discrete left/right mouse buttons, I expected pressing on the right side of the touchpad to be recognized as a right click. This is not the case.

Is this intended?

I do however see that a two finger press executes a right click.

**Comment by jackpot51** [comment]
This is intentional and not related to EC firmware, as it only bridges traffic between the touchpad and CPU

**Comment by JohnAZoidberg** [comment]
This can be configured with your input driver, for example [libinput](https://wayland.freedesktop.org/libinput/doc/latest/clickpad-softbuttons.html#clickpad-softbuttons).
