### ISSUE TITLE
oryp7 Pause/Break don't match key labels

### ISSUE THREAD

**Issue by MilesBHuff** [system76/ec#281]
On the oryp7, Fn+PgUp is labelled as "Pause" and Fn+PgDn is labelled as "Break".  However, with the latest EC, both Fn combos give Pause, while Ctrl+Fn+Either gives Break.

User expectations are for the buttons to do exactly what they are labelled for, so I have filed this bug report.

**Comment by crawfxrd** [comment]
It's intended and matches how proprietary firmware and QMK handle Pause/Break. See notes in #229.
