### ISSUE TITLE
Charger: Current divided by two

### ISSUE THREAD

**Issue by c0d3z3r0** [system76/ec#290]
https://github.com/system76/ec/blob/5ef477ab5b630c5c2684e3576a11636ffd86f07d/src/board/system76/lemp10/board.mk#L22

The reason for this is that Clevo uses R_AC=5mΩ instead of 10mΩ

**Comment by crawfxrd** [comment]
Yep. This is fixed in https://github.com/system76/ec/pull/288.

**Comment by c0d3z3r0** [comment]
Ah nice :) Didn't know but just wanted to share ;)
