### ISSUE TITLE
lemp9/galp4/darp6: Frequent suspend failures

### ISSUE THREAD

**Issue by leviport** [system76/ec#31]
I've seen it happen maybe 50% of the time on this machine. When it does, the screen goes black but never reaches suspend. The power light remains on solid, and the machine requires a hard power off. It's happening with lid close, Fn+F12, and moon icon.

**Comment by jackpot51** [comment]
Is this the same as the darp6/galp4 with new ME?

**Comment by jackpot51** [comment]
We may have to revert the ME

**Comment by leviport** [comment]
Yes the behavior is the same as galp4/darp6

**Comment by jackpot51** [comment]
Fixed by https://github.com/system76/ec/commit/7fbad82088ff534bbe5495d2080889dcebeb5788
