### ISSUE TITLE
[question] gaze16-3060 parallel.c pins for 1.0mm pitch connector

### ISSUE THREAD

**Issue by 2805852115** [system76/ec#347]
I don't know how to modify the parallel. c file（https://github.com/system76/ec/blob/master/src/board/arduino/mega2560/parallel.c）.
 Can someone send me a copy of the modified file?
I am using 1.0mm pitch connector  and gaze16-3060 model of computer.
Thank you very much.

**Comment by jacobgkau** [comment]
> I don't know how to modify the parallel. c file. Has Guys sent me a modified one?

What file are you referring to, and who is "Guys"?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by jacobgkau** [comment]
If you're talking about the pins in https://github.com/system76/ec/blob/master/src/board/arduino/mega2560/parallel.c, you'd need to say which model of computer you have for someone to give you the proper pin mapping.

**Comment by 2805852115** [comment]
> If you're talking about the pins in https://github.com/system76/ec/blob/master/src/board/arduino/mega2560/parallel.c, you'd need to say which model of computer you have for someone to give you the proper pin mapping.

Sorry, because my computer is broken and I'm in a hurry,I have revised my issue
