### ISSUE TITLE
reconfigure setting on proprietary ITE EC firmware

### ISSUE THREAD

**Issue by psyborg55** [system76/ec#372]
Hi

going through https://8051enthusiast.github.io/2021/07/05/001-EC_legacy.html it was suggested that your ecspy utility can interact with ITE chips, is this any different than what tools like RWeverything and HE do ?

the problem here is when i OC the GPU, entire system starts to draw additional power from battery.
i replaced 130W charger with 240W one, it didn't help and i can imagine why - main BIOS recognizes charger as 240W, but ITE8528E EC BIOS have only 45,65,90,130 and 150 W profiles (didn't try to modify this as i don't have an idea what these values represent, also don't have a way to flash EC BIOS on board, except for desoldering and r/w with ext programmer)

the charger IC on mainboard is BQ24780, i have entire schematic of it:
```
ChargeOption3(0X37H) [2]: Hybrid Power Boost Mode
ChargeOption0 [2]=0, Disable Hybrid Power Boost Mode <defaule>
ChargeOption0 [2]=1, Enable Hybrid Power Boost Mode--> Set
```

![sch](https://github.com/system76/ec/assets/15853469/7518d3be-25c0-4bd6-9635-71d2ceecad8e)

need a way to force this setting to disabled, hopefully some of you guys know more about this than i do

**Comment by crawfxrd** [comment]
We don't offer any support for proprietary firmware.
