### ISSUE TITLE
galp7 CPU fan speed is always 0

### ISSUE THREAD

**Issue by thomas-zimmerman** [system76/ec#396]
2023-05-25_5608a8d firmware -- both under load and if fans are set to full speed, sensors output always lists CPU fan speed as 0

**Comment by crawfxrd** [comment]
Reporting via `sensors` works on my unit running system76/firmware-open@4b4eafd7d0bc.

Strange that galp6 would be working since they're the same EC code.

Maybe fixed by 1ebc0bc6c205?

**Comment by crawfxrd** [comment]
Verified 1ebc0bc6c205 does fix the issue. I will make a new release PR.
