### ISSUE TITLE
System freezes completely on sleep with newly compiled EC on LEMP10

### ISSUE THREAD

**Issue by akoskoronka** [system76/ec#398]
I am having an interesting issue with the latest EC: when I close the lid or press the power button, normally te laptop goes to sleep and can awaken normally, but with freshly built EC, the screen remains off and the system does not react to anything including power button (>5 sec) until the battery is disconnected or completely depleted. Also when pressing side power button while the fan is spinning, the system goes to sleep with the fan on, and cannot wake up.

When I installed the old firmware+EC (2020-12-04_0e80285) via usb from the support site and even after updating the firmware+EC via gnome control center to 2022-11-21_b337ac6 all was still fine.

I started the triage, and found this commit to be the problem:
https://github.com/system76/ec/commit/3eaa5e6e0669d6afade40c2943ef2c159381aaad

**Comment by crawfxrd** [comment]
What version were you trying to use?

Sounds like https://github.com/system76/firmware-open/issues/424, which is fixed by https://github.com/system76/ec/pull/393.

**Comment by akoskoronka** [comment]
I am using firmware 2022-11-21_b337ac6 as this is the latest available with the updater.

**Comment by akoskoronka** [comment]
The latest published firmware+ec combo (2023-09-08_42bf7a6) resolved this problem.
