### ISSUE TITLE
Archlinux (possibly other fully updated distros) - Include paths aren't properly setup for the Arduino Mega Target

### ISSUE THREAD

**Issue by ilikenwf** [system76/ec#409]
I ended up having to manually specify:

`CFLAGS="-I src/board/arduino/mega2560/include -I src/arch/avr/include -I src/common/include"`

Between this and using the `--param=min-pagesize=0` CFLAG with gcc 13 (which you already set for v12) it built and flashed perfectly.

**Comment by crawfxrd** [comment]
I can build all 3 Arduino targets on Fedora 38 without modifying the `CFLAGS`.

What does a verbose build show?

```
make BOARD=arduino/mega2560 VERBOSE=1
```

**Comment by crawfxrd** [comment]
This is not reproducible on a new install of Arch.

**Comment by ilikenwf** [comment]
Strange. I may have an environmental issue then. I'll shuddup about this one.
