### ISSUE TITLE
lemp9: Battery drains when system is powered off

### ISSUE THREAD

**Issue by brs17** [system76/ec#41]
Two tests have been run where the lemp9 is turned off, noting the battery percentage then, and then turning the system on the next day and nothing the battery percentage then. In both cases, the battery percentage has dropped which leads me to believe not everything has been powered off successfully.

Test 1
Powered system off at 42% battery
23 hours later, the system was powered on again at 36% battery
0.26% battery loss per hour

Test 2
Powered system off at 8% battery
14 hours later, the system was powered on at 5% battery.
0.21% battery loss per hour

Caveat, test 1 was running an ec on the machine from mid march. The ec was then updated to the latest before running test 2.

**Comment by jackpot51** [comment]
Solved by https://github.com/system76/ec/commit/825677bfb54bda8aa31d6daafe1d3dd81654de4d

In addition, this will blink the orange light if the EC is still on but the CPU is powered down and the AC is disconnected. This was helpful in debugging for me to figure out how to turn off the EC in that state.
