### ISSUE TITLE
Q: How to make compatibility for another board?

### ISSUE THREAD

**Issue by Kreyren** [system76/ec#497]
Context: I am trying to add a compatibility for Monster T5 V23.02 for my brother which is basically identical to System76 addw3 with different CPU configuration.

Hey, i am following the guide from https://github.com/system76/firmware-open/blob/e4d1edb60841b5688122c87054928843cced4f83/docs/adding-a-new-board.md which seems to cut short from how to make the EC configuration.

I was able to generate a `gpio.c` in https://github.com/Kreyren/firmware-open/pull/1/files#diff-a3bdd8a76beeda6e0bae65d14dfc3e9d3dcd304bf7ed875319982f8ea969459f, but it's contents don't seem to be similar to the https://github.com/system76/ec/blob/face3813542392df35e232b867d888a69e6789c4/src/board/system76/addw3/gpio.c

It also generated `hda_verb.c` in https://github.com/Kreyren/firmware-open/pull/1/files#diff-a2211aff03d6af884cc2ba4111118191a6c2474f6c243f9becb0d4275af4c9fa that i don't know what to do with atm.

FWIW i think that i am able to get a functional coreboot for the device(using the addw3's config and changing `SOC_INTEL_ALDERLAKE_PCH_P`), but i am stuck at getting the EC rn

Thanks for anything relevant! <3

EDIT: Found https://github.com/system76/ec/blob/master/docs/adding-a-new-board.md

> Use the EC page in the schematics to label everything.

I don't have the schematics, does that mean that i have to identify the GPIOs via oscilloscope ? 

EDIT: Actually gaze17 https://tech-docs.system76.com/models/gaze17/README.html looks to be exactly identical in terms of how the PCB looks just different GPU configuration and CPU being i7-12650 vs i7-12700 and uses the same charger

**Comment by crawfxrd** [comment]
- gaze17-3050 is Clevo NP7[01]PN[HJK]
- gaze17-3060-b is Clevo NP5[05]PNP

You will not be able to verify components and pin configuration without schematics. You would also need to figure out the keyboard matrix layout for the ISO keyboard.

You can use the proprietary firmware with the [clevo/it5570e](https://github.com/coreboot/coreboot/tree/24.05/src/ec/clevo/it5570e) interface from 3mdeb in coreboot instead.
