### ISSUE TITLE
Intel CPU power-on functionality

### ISSUE THREAD

**Issue by loftlifter31** [system76/ec#502]
I tried replacing the stock Intel MEv15 which comes with galp5 with an older one from galp3 MEv11. The reason being me_cleaner python script doesn't support MEv15 but does support MEv11. Unfortunately the CPU will not power on with the older ME. My research indicates this is because the newer ME which comes with Tigerlake includes a CPU power on function. Without that function the laptop will not power up.

The galp3 which the MEv11 came from didn't have any issues powering up without this ME function, so I'm assuming the version of EC which shipped with this laptop included the function to power up, which the newer EC apparently lacks.  Would it be possible to use the older EC from the galp3 on a galp5 to overcome this limitation? Or maybe just import the code for the powerup function?

**Comment by crawfxrd** [comment]
CSME versions are tied to the SoC. You _have_ to use 15.0 on a TGL platform.
