### ISSUE TITLE
Disable key repeat on certain hotkeys

### ISSUE THREAD

**Issue by leviport** [system76/ec#74]
On lemp9 and oryp6 I noticed that holding Fn+F2 makes the display strobe on and off. We should probably disable key repeating on that hotkey, as well as some others.

The only ones where I think we would want it are:
* Volume up and down: Fn + F5 and F6
* Display brightness up and down: Fn + F8 and F9
* Keyboard brightness up/down (for the machines that have up and down for keyboard brightness, at least)

Lemp9's keyboard light level hotkey (Fn+F4) should maybe also have repeating turned off as well. It looks cool, but doesn't seem useful in practice.

**Comment by crawfxrd** [comment]
Disabling repeat won't matter for normal keys because GNOME implements its own key repeat to control these (Universal Access > Typing > Repeat Keys).
